load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_binary(
    name = "lox-cpp",
    srcs = ["main.cpp"],
    deps = [
        "//lib:liblox",
    ],
)
